
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[] =
{
	{
		XPAR_ETHERNET100M_DEVICE_ID,
		XPAR_ETHERNET100M_BASEADDR,
		XPAR_ETHERNET100M_TX_PING_PONG,
		XPAR_ETHERNET100M_RX_PING_PONG,
		XPAR_ETHERNET100M_INCLUDE_MDIO,
		XPAR_ETHERNET100M_INCLUDE_INTERNAL_LOOPBACK
	}
};


