
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_I2C_INTERFACE_DEVICE_ID,
		XPAR_I2C_INTERFACE_BASEADDR,
		XPAR_I2C_INTERFACE_TEN_BIT_ADR,
		XPAR_I2C_INTERFACE_GPO_WIDTH
	}
};


